### ISSUE TITLE
Access to second built-in skin

### ISSUE THREAD

**Issue by drbubbles** [vitotai/BrewPiLessGx#3]
I have an ESP32_2432S032C and Pill but I don't see how to switch to the Pill skin (the pill was detected and selected in the gravity tab on the web interface).
I tried adding:
        src/skins/skin_brewpi19.json
        src/skins/skin_hydro19.json

to the [env:ESP32_2432S032C] section of platformio.ini  (copied from [env:ESP32_17320S019N])  but that didn't appear to help.

How do I get to the Pill skin? I can see the main skin with temperature and access to wifi settings.  (This and the rest of brewpiless is absolutely fantastic by the way!)

**Comment by drbubbles** [comment]
@DMT07 thanks, that worked for me too (I'm using an ESP32_2432S032C). Will see if I can make a couple of one-wire controlled relays (need to figure out parts to order). Like @vitotai pointed out, there's one less IO pin available than required for both heating and cooling control ( at least on the ESP32_2432S032C).   Unless maybe one of the IOs isn't being used (or is used for something we don't require) and could be got at with a soldering iron.

**Comment by drbubbles** [comment]
Thanks @DMT07, having looked at the board I'm a bit worried about strain relief for any wires I solder there. I have a wired pressure gauge and realized I need 2 extra IO ports as I also would like to use a solenoid. So I plan to use  a few DS2413 modules like @vitotai suggested. I'll post a picture if I get it going. Then I need to tackle interfacing an esp32 to the replacement induction hob controller I just got off AliExpress for mashing (I blew up the original one trying to automate it!)

**Comment by vitotai** [comment]
Sorry. I was busy and had no time to come back to this project.
Somehow, I forgot to add the code, or some part of code was removed by accident. The skin skin switch code wasn't there...

Just updated it. I also created a simple skin editor. It's buggy and not complete, but it helps in positioning and sizing text elements of skins.

**Comment by drbubbles** [comment]
Thanks for the update, I did as you recommend, I added DS3413 1-wire to control the relays. So now on 1-wire i have: cool, heat, pressure release valve, beer temp, room temp. The pressure gauge goes direct to pin 35 (no adc), and there's a Pill on bluetooth (works through jacketed conical fermenter). I put phono plugs on the relays so I can remove them easily, and audio jacks for the sensors.   

Now I just need to mount it all in a box or maybe on a piece of wood! 

![1](https://github.com/vitotai/BrewPiLessGx/assets/6434173/69f3119b-638f-4276-b17b-d3523f79940c)

**Comment by Hwerow** [comment]
@drbubbles Please could you sketch out the circuit connections Thanks

**Comment by drbubbles** [comment]
@hweror I put this together to describe it, I don't have an actual wiring diagram. I think this covers all the connections requires. 

![image](https://github.com/vitotai/BrewPiLessGx/assets/6434173/9ac998f8-b53e-47a4-b0d3-97609465c6d6)

**Comment by Hwerow** [comment]
@drbubbles thanks that helps Cheers

**Comment by drbubbles** [comment]
> Sorry. I was busy and had no time to come back to this project. Somehow, I forgot to add the code, or some part of code was removed by accident. The skin skin switch code wasn't there...
> 
> Just updated it. I also created a simple skin editor. It's buggy and not complete, but it helps in positioning and sizing text elements of skins.

@vitotai Did this update enable a build flag to select one of the skins listed as default?  I can change it using the backup json file like @DMT07 pointed out but I was hoping to select the info one for a fresh install (along with the pre-defined wifi settings, sorry, I should have posted that question here rather than in homebrewtalk forum). 
        src/skins/skin_brewpi3224.json
->    src/skins/skin_info3224.json
